version: '3'

services:
  # localhost friendly vector-similarity search database
  qdrant:
    image: qdrant/qdrant
    environment:
      QDRANT__SERVICE__GRPC_PORT: "6334"
    ports:
    - "6333:6333"
    - "6334:6334"
