[build]
builder = "paketobuildpacks/builder:0.3.249-base"
buildpacks = ["gcr.io/paketo-buildpacks/go:4.3.5"]

[build.args]
BP_GO_VERSION = "1.20.3"
BP_GO_TARGETS = "./aip-wiki/cmd/wikid"

[env]
MILVUS_HOST="in01-56f0a7dbf08d4a1.aws-us-east-2.vectordb.zillizcloud.com"
MILVUS_PORT="19537"

MILVUS_ENDPOINT="https://in01-56f0a7dbf08d4a1.aws-us-east-2.vectordb.zillizcloud.com:19537"
MILVUS_USERNAME="db_admin"

AIP_FORD_STORAGE_MEMGRAPH_CONNECTION_URI="bolt+ssc://54.152.19.198:7687"
AIP_FORD_STORAGE_MEMGRAPH_USERNAME="aip"

OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf"
OTEL_EXPORTER_OTLP_ENDPOINT="https://otlp-gateway-prod-us-central-0.grafana.net/otlp"
OTEL_EXPORTER_OTLP_HEADERS="Authorization=Basic NjQyNTExOmV5SnJJam9pTVRCaE9ESm1abUV4TXpVMlpETXpZbVUzTVdSa04ySXdZV0V6TnpWallqZGpOVGN3TldObVpTSXNJbTRpT2lKaGFYQXRkMmxyYVNJc0ltbGtJam80TlRVd016Ujk="

[http_service]
internal_port = 30100
force_https = true
auto_stop_machines = false
auto_start_machines = false

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[metrics]
port = 30100
path = "/metrics"
